
#####################
####  Database   ####
#####################
services:

  vdi:
    depends_on:
      edapostgres:
        condition: service_healthy

  eda:
    depends_on:
      edapostgres:
        condition: service_healthy

  wdk:
    depends_on:
      edapostgres:
        condition: service_healthy

  edapostgres:
    build:
      context: ./postgres-build
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: eda
      PGPORT: 5434
      VDI_SCHEMA_SUFFIX: ${VDI_SCHEMA_SUFFIX}
      VDI_DB_PASSWD: ${DB_CONNECTION_PASS_MICROBIOME}

    networks:
      - internal
    volumes:
      - type: bind
        source: ${DATA_STORAGE_ROOT_DIR}/persistentData/postgres
        target: /var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=${VDI_POSTGRES_WATCHTOWER:-false}"
    ports:
      - 5434:5434
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_ROOT_USER} -d eda -p 5434"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s