
psql --set "USER=${POSTGRES_USER}" -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-END

CREATE SCHEMA :"USER";

CREATE TABLE :"USER".QUERYINSTANCE
   (	WDK_INSTANCE_ID NUMERIC(12,0) NOT NULL,
	QUERY_NAME VARCHAR(200) NOT NULL,
	TABLE_NAME VARCHAR(30) NOT NULL,
	INSTANCE_CHECKSUM VARCHAR(40) NOT NULL,
	PARAMS JSON,
  RESULT_MESSAGE JSON,
	 CONSTRAINT PK_WDK_INSTANCE_ID PRIMARY KEY (WDK_INSTANCE_ID)
  );

CREATE TABLE :"USER".STEP_ANALYSIS_RESULTS
   (	CONTEXT_HASH VARCHAR(96) NOT NULL,
	STATUS VARCHAR(96),
	START_DATE TIMESTAMP (6),
	UPDATE_DATE TIMESTAMP (6),
	TIMEOUT_MINS NUMERIC(10,0),
	LOG JSON,
	CHAR_DATA JSON,
	BIN_DATA bytea,
	 PRIMARY KEY (CONTEXT_HASH)
	 );

CREATE SEQUENCE :"USER".QUERYINSTANCE_PKSEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999999999999;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA :"USER" TO :"USER";

END